debug = false
logLevel = "ERROR"

defaultEntryPoints = ["http"]

[web]
# Port for the status/dashboard page
address = ":8080"

[entryPoints]
    [entryPoints.http]
    address = ":80"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "nmoller.io"
watch = true
exposedByDefault = false